// flow-typed signature: 797d6098e99f12044dddaf29c2496602
// flow-typed version: <<STUB>>/babel-node-debug_v2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-node-debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-node-debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-node-debug/bin/_babel-node' {
  declare module.exports: any;
}

declare module 'babel-node-debug/bin/babel-node' {
  declare module.exports: any;
}

declare module 'babel-node-debug/bin/bode-debug' {
  declare module.exports: any;
}

declare module 'babel-node-debug/bin/bode-inspector' {
  declare module.exports: any;
}

declare module 'babel-node-debug/lib/Debugger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-node-debug/bin/_babel-node.js' {
  declare module.exports: $Exports<'babel-node-debug/bin/_babel-node'>;
}
declare module 'babel-node-debug/bin/babel-node.js' {
  declare module.exports: $Exports<'babel-node-debug/bin/babel-node'>;
}
declare module 'babel-node-debug/bin/bode-debug.js' {
  declare module.exports: $Exports<'babel-node-debug/bin/bode-debug'>;
}
declare module 'babel-node-debug/bin/bode-inspector.js' {
  declare module.exports: $Exports<'babel-node-debug/bin/bode-inspector'>;
}
declare module 'babel-node-debug/lib/Debugger.js' {
  declare module.exports: $Exports<'babel-node-debug/lib/Debugger'>;
}
