// flow-typed signature: b776a1d3144bcb8617aa4efc1fbcb383
// flow-typed version: <<STUB>>/firebase-admin_v4.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-admin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-admin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-admin/lib/auth/auth-api-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/auth' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/credential' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/register-auth' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/token-generator' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/user-record' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/database/database' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/default-namespace' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/firebase-namespace' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/firebase-service' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/index' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/api-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/deep-copy' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/error' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-admin/lib/auth/auth-api-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/auth-api-request'>;
}
declare module 'firebase-admin/lib/auth/auth.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/auth'>;
}
declare module 'firebase-admin/lib/auth/credential.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/credential'>;
}
declare module 'firebase-admin/lib/auth/register-auth.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/register-auth'>;
}
declare module 'firebase-admin/lib/auth/token-generator.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/token-generator'>;
}
declare module 'firebase-admin/lib/auth/user-record.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/user-record'>;
}
declare module 'firebase-admin/lib/database/database.js' {
  declare module.exports: $Exports<'firebase-admin/lib/database/database'>;
}
declare module 'firebase-admin/lib/default-namespace.js' {
  declare module.exports: $Exports<'firebase-admin/lib/default-namespace'>;
}
declare module 'firebase-admin/lib/firebase-app.js' {
  declare module.exports: $Exports<'firebase-admin/lib/firebase-app'>;
}
declare module 'firebase-admin/lib/firebase-namespace.js' {
  declare module.exports: $Exports<'firebase-admin/lib/firebase-namespace'>;
}
declare module 'firebase-admin/lib/firebase-service.js' {
  declare module.exports: $Exports<'firebase-admin/lib/firebase-service'>;
}
declare module 'firebase-admin/lib/index.js' {
  declare module.exports: $Exports<'firebase-admin/lib/index'>;
}
declare module 'firebase-admin/lib/utils/api-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/api-request'>;
}
declare module 'firebase-admin/lib/utils/deep-copy.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/deep-copy'>;
}
declare module 'firebase-admin/lib/utils/error.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/error'>;
}
declare module 'firebase-admin/lib/utils/validator.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/validator'>;
}
