// flow-typed signature: d040ad75ace5e5ebe5d75af64111b9eb
// flow-typed version: <<STUB>>/model-base_v1.1.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'model-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'model-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'model-base/gulpfile' {
  declare module.exports: any;
}

declare module 'model-base/lib/model_collection' {
  declare module.exports: any;
}

declare module 'model-base/lib/model_utilities' {
  declare module.exports: any;
}

declare module 'model-base/lib/model_validator' {
  declare module.exports: any;
}

declare module 'model-base/lib/model' {
  declare module.exports: any;
}

declare module 'model-base/tests/AbstractModel' {
  declare module.exports: any;
}

declare module 'model-base/tests/AbstractModelCollection' {
  declare module.exports: any;
}

declare module 'model-base/tests/AbstractModelUtilities' {
  declare module.exports: any;
}

declare module 'model-base/tests/AbstractModelValidator' {
  declare module.exports: any;
}

declare module 'model-base/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'model-base/gulpfile.js' {
  declare module.exports: $Exports<'model-base/gulpfile'>;
}
declare module 'model-base/index' {
  declare module.exports: $Exports<'model-base'>;
}
declare module 'model-base/index.js' {
  declare module.exports: $Exports<'model-base'>;
}
declare module 'model-base/lib/model_collection.js' {
  declare module.exports: $Exports<'model-base/lib/model_collection'>;
}
declare module 'model-base/lib/model_utilities.js' {
  declare module.exports: $Exports<'model-base/lib/model_utilities'>;
}
declare module 'model-base/lib/model_validator.js' {
  declare module.exports: $Exports<'model-base/lib/model_validator'>;
}
declare module 'model-base/lib/model.js' {
  declare module.exports: $Exports<'model-base/lib/model'>;
}
declare module 'model-base/tests/AbstractModel.js' {
  declare module.exports: $Exports<'model-base/tests/AbstractModel'>;
}
declare module 'model-base/tests/AbstractModelCollection.js' {
  declare module.exports: $Exports<'model-base/tests/AbstractModelCollection'>;
}
declare module 'model-base/tests/AbstractModelUtilities.js' {
  declare module.exports: $Exports<'model-base/tests/AbstractModelUtilities'>;
}
declare module 'model-base/tests/AbstractModelValidator.js' {
  declare module.exports: $Exports<'model-base/tests/AbstractModelValidator'>;
}
declare module 'model-base/tests/index.js' {
  declare module.exports: $Exports<'model-base/tests/index'>;
}
