// flow-typed signature: 75317e0d47a317e10b2c210fbe2aeb2a
// flow-typed version: <<STUB>>/sidekick_v1.12.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sidekick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sidekick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sidekick/sidekick' {
  declare module.exports: any;
}

declare module 'sidekick/src/analysers' {
  declare module.exports: any;
}

declare module 'sidekick/src/config' {
  declare module.exports: any;
}

declare module 'sidekick/src/flow' {
  declare module.exports: any;
}

declare module 'sidekick/src/gui-control' {
  declare module.exports: any;
}

declare module 'sidekick/src/index.integration' {
  declare module.exports: any;
}

declare module 'sidekick/src/index' {
  declare module.exports: any;
}

declare module 'sidekick/src/init' {
  declare module.exports: any;
}

declare module 'sidekick/src/MainProcess' {
  declare module.exports: any;
}

declare module 'sidekick/src/open' {
  declare module.exports: any;
}

declare module 'sidekick/src/prepush-hook-file' {
  declare module.exports: any;
}

declare module 'sidekick/src/prepush-ui-non-tty' {
  declare module.exports: any;
}

declare module 'sidekick/src/prepush-ui-tty' {
  declare module.exports: any;
}

declare module 'sidekick/src/prepush-ui-tty.test' {
  declare module.exports: any;
}

declare module 'sidekick/src/prepush-ui' {
  declare module.exports: any;
}

declare module 'sidekick/src/prepush' {
  declare module.exports: any;
}

declare module 'sidekick/src/reporters/cliSummary' {
  declare module.exports: any;
}

declare module 'sidekick/src/reporters/jsonStream' {
  declare module.exports: any;
}

declare module 'sidekick/src/reporters/junit' {
  declare module.exports: any;
}

declare module 'sidekick/src/reporters/junitTest.test' {
  declare module.exports: any;
}

declare module 'sidekick/src/reporters/scenario.test' {
  declare module.exports: any;
}

declare module 'sidekick/src/run' {
  declare module.exports: any;
}

declare module 'sidekick/src/run.test' {
  declare module.exports: any;
}

declare module 'sidekick/src/safeSpawn' {
  declare module.exports: any;
}

declare module 'sidekick/src/safeSpawn.test' {
  declare module.exports: any;
}

declare module 'sidekick/src/streamReconnect' {
  declare module.exports: any;
}

declare module 'sidekick/src/streamReconnect.test' {
  declare module.exports: any;
}

declare module 'sidekick/src/textUi' {
  declare module.exports: any;
}

declare module 'sidekick/src/textUi.test' {
  declare module.exports: any;
}

declare module 'sidekick/test/fixtures/safeSpawnFixture' {
  declare module.exports: any;
}

declare module 'sidekick/test/fixtures/testRepo/testFile' {
  declare module.exports: any;
}

declare module 'sidekick/test/runTest' {
  declare module.exports: any;
}

declare module 'sidekick/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sidekick/sidekick.js' {
  declare module.exports: $Exports<'sidekick/sidekick'>;
}
declare module 'sidekick/src/analysers.js' {
  declare module.exports: $Exports<'sidekick/src/analysers'>;
}
declare module 'sidekick/src/config.js' {
  declare module.exports: $Exports<'sidekick/src/config'>;
}
declare module 'sidekick/src/flow.js' {
  declare module.exports: $Exports<'sidekick/src/flow'>;
}
declare module 'sidekick/src/gui-control.js' {
  declare module.exports: $Exports<'sidekick/src/gui-control'>;
}
declare module 'sidekick/src/index.integration.js' {
  declare module.exports: $Exports<'sidekick/src/index.integration'>;
}
declare module 'sidekick/src/index.js' {
  declare module.exports: $Exports<'sidekick/src/index'>;
}
declare module 'sidekick/src/init.js' {
  declare module.exports: $Exports<'sidekick/src/init'>;
}
declare module 'sidekick/src/MainProcess.js' {
  declare module.exports: $Exports<'sidekick/src/MainProcess'>;
}
declare module 'sidekick/src/open.js' {
  declare module.exports: $Exports<'sidekick/src/open'>;
}
declare module 'sidekick/src/prepush-hook-file.js' {
  declare module.exports: $Exports<'sidekick/src/prepush-hook-file'>;
}
declare module 'sidekick/src/prepush-ui-non-tty.js' {
  declare module.exports: $Exports<'sidekick/src/prepush-ui-non-tty'>;
}
declare module 'sidekick/src/prepush-ui-tty.js' {
  declare module.exports: $Exports<'sidekick/src/prepush-ui-tty'>;
}
declare module 'sidekick/src/prepush-ui-tty.test.js' {
  declare module.exports: $Exports<'sidekick/src/prepush-ui-tty.test'>;
}
declare module 'sidekick/src/prepush-ui.js' {
  declare module.exports: $Exports<'sidekick/src/prepush-ui'>;
}
declare module 'sidekick/src/prepush.js' {
  declare module.exports: $Exports<'sidekick/src/prepush'>;
}
declare module 'sidekick/src/reporters/cliSummary.js' {
  declare module.exports: $Exports<'sidekick/src/reporters/cliSummary'>;
}
declare module 'sidekick/src/reporters/jsonStream.js' {
  declare module.exports: $Exports<'sidekick/src/reporters/jsonStream'>;
}
declare module 'sidekick/src/reporters/junit.js' {
  declare module.exports: $Exports<'sidekick/src/reporters/junit'>;
}
declare module 'sidekick/src/reporters/junitTest.test.js' {
  declare module.exports: $Exports<'sidekick/src/reporters/junitTest.test'>;
}
declare module 'sidekick/src/reporters/scenario.test.js' {
  declare module.exports: $Exports<'sidekick/src/reporters/scenario.test'>;
}
declare module 'sidekick/src/run.js' {
  declare module.exports: $Exports<'sidekick/src/run'>;
}
declare module 'sidekick/src/run.test.js' {
  declare module.exports: $Exports<'sidekick/src/run.test'>;
}
declare module 'sidekick/src/safeSpawn.js' {
  declare module.exports: $Exports<'sidekick/src/safeSpawn'>;
}
declare module 'sidekick/src/safeSpawn.test.js' {
  declare module.exports: $Exports<'sidekick/src/safeSpawn.test'>;
}
declare module 'sidekick/src/streamReconnect.js' {
  declare module.exports: $Exports<'sidekick/src/streamReconnect'>;
}
declare module 'sidekick/src/streamReconnect.test.js' {
  declare module.exports: $Exports<'sidekick/src/streamReconnect.test'>;
}
declare module 'sidekick/src/textUi.js' {
  declare module.exports: $Exports<'sidekick/src/textUi'>;
}
declare module 'sidekick/src/textUi.test.js' {
  declare module.exports: $Exports<'sidekick/src/textUi.test'>;
}
declare module 'sidekick/test/fixtures/safeSpawnFixture.js' {
  declare module.exports: $Exports<'sidekick/test/fixtures/safeSpawnFixture'>;
}
declare module 'sidekick/test/fixtures/testRepo/testFile.js' {
  declare module.exports: $Exports<'sidekick/test/fixtures/testRepo/testFile'>;
}
declare module 'sidekick/test/runTest.js' {
  declare module.exports: $Exports<'sidekick/test/runTest'>;
}
declare module 'sidekick/test/setup.js' {
  declare module.exports: $Exports<'sidekick/test/setup'>;
}
